# Dependencies
plugins:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - jekyll-sitemap

markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Fifteen Lines of Fame
tagline:          'All-purpose elixir'
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:      '[writing, code, family]'
url:              https://www.fifteenlinesoffame.com
baseurl:          /

author:
  name:           'Ben Patterson aka Ben Madrone'
  url:            https://twitter.com/benmadrone

paginate:         5

redcarpet:
  extensions: ["footnotes"]

exclude:        ["_draft"]

# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/benpatterson/benpatterson.github.io
