baseURL: https://www.fifteenlinesoffame.com
disablePathToLower: true
languageCode: en-us
title: Fifteen Lines of Fame
theme: Hyde

menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about/
  - identifier: subscribe
    name: Subscribe
    title: Subscribe
    url: /subscribe/
